sudo: required
services:
    - docker

before_install:
    - docker build -t kansodocker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true  kansodocker/docker-react npm run test

language: generic