# version of docker-compose
version: '3'
# think about services as containers
services:
    web:
      environment: 
        - CHOKIDAR_USEPOLLING=true
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes: 
        - /app/node_modules
        - .:/app
      stdin_open: true
    tests:
      environment: 
        - CHOKIDAR_USEPOLLING=true
      build: 
        context: .
        dockerfile: Dockerfile.dev
      volumes: 
        - /app/node_modules
        - .:/app
      stdin_open: true
      command: ["npm","run","test"]